[[plugins]]
  package = "@netlify/plugin-lighthouse"

[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = '''
	  max-age=63072000;
	  includeSubDomains;
	  preload'''

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["cssnano-preset-simple"]
